### ISSUE TITLE
有关于item_freq_dict_norm.txt

### ISSUE THREAD

**Issue by YannnnnnY** [summmeer/session-based-news-recommendation#1]
作者您好，我在复现session-based-news-recommendation这一项目时遇到了一些问题，按照readme文件提示进行数据预处理后还是找不到item_freq_dict_norm_1.txt等文件，所以想请教一下这个文件是在哪个程序中生成的，谢谢。

**Comment by summmeer** [comment]
This is used to compute ESIR score, which we didn't use at last, so this line can be removed

**Comment by YannnnnnY** [comment]
很感谢您的回复，问题已解决。如果方便的话，可以告知我们：该项目在globo数据集上训练的大概时间以及你们所用的硬件配置吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "summmeer/session-based-news-recommendation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月1日(星期三) 晚上8:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [summmeer/session-based-news-recommendation] 有关于item_freq_dict_norm.txt (Issue #1)





 
This is used to compute ESIR score, which we didn't use at last, so this line can be removed

**Comment by summmeer** [comment]
We trained our model on the Globo dataset using one GTX 1080 Ti, and the training time is within a few hours (3~4 hours).

**Comment by YannnnnnY** [comment]
感谢您的回复，我们在复现的过程中，使用了一张RTX 2080 Ti在globo数据集上训练，但不知为何已经训练了40多个小时还未完成epoch1，想问一下你们在训练完之后有没有保存模型的权重，如果有的话可以发送给我吗，谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "summmeer/session-based-news-recommendation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月4日(星期六) 凌晨0:47
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [summmeer/session-based-news-recommendation] 有关于item_freq_dict_norm.txt (Issue #1)





 
We trained our model on the Globo dataset using one GTX 1080 Ti, and the training time is within a few hours (3~4 hours).

**Comment by summmeer** [comment]
Sorry I didn't keep the model. Maybe you could paste your training log and see what's wrong here.

**Comment by YannnnnnY** [comment]
没事没事，其实我是上海财经大学信息管理与工程学院的本科生，目前刚入门推荐系统和深度学习的内容，因此在复现的过程中问题比较多，感谢您一直以来的回复。
如果方便的话，您可以给我您的微信方便我问一些琐碎的问题吗，或者您也可以加一下我的微信：18918821601，万分感谢。
train的过程中输出的内容如附件所示，我不太确定这是不是您所说的training log，这是我用RTX 2080ti在globo数据集上训练了约50个小时得到的结果。
还有一个疑问，就是无论我将batch_size设成4096，还是512，还是1，用nvidia-smi指令看到的显存占用率都是几乎满的，但显卡的利用率却很低，想请教一下这是正常的现象吗？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "summmeer/session-based-news-recommendation"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月4日(星期六) 下午5:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [summmeer/session-based-news-recommendation] 有关于item_freq_dict_norm.txt (Issue #1)





 
Sorry I didn't keep the model. Maybe you could paste your training log and see what's wrong here.

**Comment by summmeer** [comment]
I didn't see your log, could you paste it in this github issue? I'm sorry I can't answer you more about GPU things, which is beyond this paper. There're many tutorials in the Internet.

**Comment by Friest-a11y** [comment]
作者您好，我在使用您的源码时，出现了这样的问题，请问是哪里需要修改嘛

Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/session-based-news-recommendation-master改动版/main.py", line 128, in <module>
    main(args)
  File "C:/Users/Administrator/Desktop/session-based-news-recommendation-master改动版/main.py", line 67, in main
    model = getattr(modelname, "Seq2SeqAttNN")(args)
  File "C:\Users\Administrator\Desktop\session-based-news-recommendation-master改动版\model_combine.py", line 116, in __init__
    scope="multi_attention", hidden_size=self.hidden_size, stddev=self.stddev)
  File "C:\Users\Administrator\Desktop\session-based-news-recommendation-master改动版\modules.py", line 132, in multi_attention_layer
    stddev)  # [batch_size, time_step]
  File "C:\Users\Administrator\Desktop\session-based-news-recommendation-master改动版\modules.py", line 151, in count_alpha_m
    active=None)  # [batch_size, time_step, hidden_size]
  File "C:\Users\Administrator\Desktop\session-based-news-recommendation-master改动版\modules.py", line 76, in linear_3d
    res = tf.matmul(inputs, w)
  File "D:\python\lib\site-packages\tensorflow_core\python\util\dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "D:\python\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 2716, in matmul
    return batch_mat_mul_fn(a, b, adj_x=adjoint_a, adj_y=adjoint_b, name=name)
  File "D:\python\lib\site-packages\tensorflow_core\python\ops\gen_math_ops.py", line 1712, in batch_mat_mul_v2
    "BatchMatMulV2", x=x, y=y, adj_x=adj_x, adj_y=adj_y, name=name)
  File "D:\python\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "D:\python\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\python\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "D:\python\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "D:\python\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1770, in __init__
    control_input_ops)
  File "D:\python\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 64 and 1 for 'multi_attention/inter_linear_trans/MatMul' (op: 'BatchMatMulV2') with input shapes: [?,?,64], [?,1,250].

**Comment by summmeer** [comment]
@Yang-Yan-Yang-Yan Hi, I update the getILD function, for Globo dataset, the original one costs a lot of time, and seems like dead loop. I think now the training time can be normal.

**Comment by nibyig** [comment]
其实啊，这不是死循环，只要花费五十个小时就可以跑完一个epoch（不要问我如何知道）
